#!/usr/bin/env python3
import sys
import os
import subprocess
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

TOKEN = "8187479612:AAE3ZF-qItlSd2MhoZX2e0NbvTBaeAVemhc"
CHAT_ID = "7250558059"

def send_file(filepath):
    filename = os.path.basename(filepath)
    cmd = ["curl", "-s", "-F", f"chat_id={CHAT_ID}", "-F", f"document=@{filepath}", "-F", f"caption=Laporan Lengkap AI - 20+ Halaman", f"https://api.telegram.org/bot{TOKEN}/sendDocument"]
    subprocess.run(cmd, capture_output=True)

def add_para(doc, text):
    p = doc.add_paragraph(text)
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    return p

def add_bold(doc, text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    return p

def add_heading(doc, text):
    h = doc.add_heading(text, level=1)
    if h.runs:
        h.runs[0].font.size = Pt(14)
    return h

def buat_laporan():
    doc = Document()
    doc.styles["Normal"].font.name = "Times New Roman"
    doc.styles["Normal"].font.size = Pt(12)

    # COVER
    doc.add_paragraph()
    doc.add_paragraph()
    p = doc.add_paragraph("LAPORAN AKHIR")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].bold = True
    p.runs[0].font.size = Pt(20)
    
    doc.add_paragraph()
    p = doc.add_paragraph("STUDI KOMPREHENSIF TENTANG")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].font.size = Pt(16)
    
    doc.add_paragraph()
    p = doc.add_paragraph("ARTIFICIAL INTELLIGENCE (AI)")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].bold = True
    p.runs[0].font.size = Pt(24)
    
    doc.add_paragraph()
    p = doc.add_paragraph("KECERDASAN BUATAN DALAM MASA MODERN")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].font.size = Pt(16)
    
    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()
    
    for label, nilai in [("Nama", "Ahdi Khalida Fathir"), ("Kelas", "X IPA"), ("Mata Pelajaran", "Informatika"), ("Sekolah", "SMAN 1"), ("Tahun Pelajaran", "2025/2026"), ("Tanggal Penyerahan", "April 2026")]:
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(nilai)
    
    doc.add_page_break()

    # KATA PENGANTAR
    p = doc.add_paragraph("KATA PENGANTAR")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.runs[0].bold = True
    p.runs[0].font.size = Pt(14)
    
    add_para(doc, "Puji dan syukur penulis panjatkan kehadirat Tuhan Yang Maha Esa, karena atas berkat rahmat dan karunia-Nya, penulis dapat menyelesaikan laporan ini dengan baik dan tepat waktu.")
    add_para(doc, "Laporan ini disusun untuk memenuhi tugas akhir mata pelajaran Informatika mengenai Artificial Intelligence (AI) atau Kecerdasan Buatan. Dalam laporan ini, penulis berusaha mengupas secara komprehensif mengenai konsep, sejarah, perkembangan, jenis-jenis, teknologi, implementasi, dampak, serta prospek masa depan dari teknologi AI.")
    add_para(doc, "Penulis menyadari bahwa laporan ini masih jauh dari sempurna. Oleh karena itu, penulis sangat mengharapkan kritik dan saran yang membangun dari pembaca demi perbaikan dan penyempurnaan laporan ini di masa yang akan datang.")
    add_para(doc, "Semoga laporan ini dapat memberikan manfaat dan menambah wawasan pembaca mengenai teknologi Artificial Intelligence yang semakin berkembang pesat di era digital saat ini.")
    
    doc.add_paragraph()
    add_para(doc, "                                                                       Penulis")
    add_para(doc, "                                                                       Ahdi Khalida Fathir")
    
    doc.add_page_break()

    # BAB I - PENDAHULUAN
    add_heading(doc, "BAB I. PENDAHULUAN")
    
    add_bold(doc, "1.1 Latar Belakang")
    add_para(doc, "Perkembangan teknologi informasi dan komunikasi pada abad ke-21 telah membawa perubahan fundamental dalam berbagai aspek kehidupan manusia. Salah satu teknologi yang paling dominan dan membawa dampak signifikan adalah Artificial Intelligence atau yang dikenal dengan istilah Kecerdasan Buatan. Teknologi ini telah mengubah cara manusia bekerja, berkomunikasi, belajar, dan bahkan berpikir.")
    add_para(doc, "Artificial Intelligence atau AI merupakan simulasi dari proses kecerdasan manusia yang dilakukan oleh mesin, khususnya sistem komputer. Proses ini mencakup pembelajaran (aquiring information and rules for using the information), penalaran (using rules to reach approximate or definite conclusions), dan koreksi diri (self-correction). Konsep AI pertama kali diperkenalkan pada tahun 1956 oleh John McCarthy di Dartmouth Conference, dan sejak saat itu, teknologi ini telah mengalami beberapa kali revolusi yang mengubah paradigma kehidupan manusia.")
    add_para(doc, "Pada awalnya, AI hanya mampu menyelesaikan tugas-tugas sederhana yang bersifat deterministik. Namun, dengan adanya kemajuan dalam bidang komputasi, algoritma machine learning, dan ketersediaan data dalam jumlah besar (big data), kemampuan AI telah berkembang luar biasa. Saat ini, AI mampu melakukan hal-hal yang sebelumnya dianggap mustahil, seperti mengenali wajah dengan akurasi tinggi, menerjemahkan bahasa secara real-time, mengemudikan kendaraan secara otonom, hingga menciptakan karya seni dan musik yang orisinal.")
    add_para(doc, "Pengaruh AI telah merambah ke hampir semua sektor kehidupan. Di bidang kesehatan, AI membantu dokter dalam mendiagnosis penyakit dengan lebih akurat. Di bidang pendidikan, AI mempersonalisasi pengalaman belajar siswa. Di bidang ekonomi, AI mengoptimalkan proses trading dan analisis risiko. Di bidang hiburan, AI merekomendasikan konten yang sesuai dengan preferensi pengguna. Bahkan di bidang pemerintahan, AI digunakan untuk meningkatkan efisiensi layanan publik dan pengambilan keputusan kebijakan.")
    add_para(doc, "Namun, di balik manfaat yang begitu besar, AI juga membawa berbagai tantangan dan ancaman yang perlu mendapatkan perhatian serius. Issuelebaran seperti pengangguran akibat automasi, bias algoritma, pelanggaran privasi, keamanan siber, hingga pertanyaan etis tentang hak dan moralitas mesin cerdas menjadi topik diskusi yang semakin relevan di era AI saat ini.")
    add_para(doc, "Berdasarkan latar belakang tersebut, penulis tertarik untuk menyusun laporan yang komprehensif mengenai Artificial Intelligence. Laporan ini bertujuan untuk memberikan pemahaman mendalam mengenai berbagai aspek AI, mulai dari konsep dasar hingga implikasi di masa depan, sehingga pembaca dapat memahami secara utuh mengenai teknologi yang akan shape masa depan umat manusia.")
    
    add_bold(doc, "1.2 Rumusan Masalah")
    add_para(doc, "Berdasarkan latar belakang yang telah diuraikan, maka rumusan masalah dalam laporan ini adalah:")
    add_para(doc, "1. Apa pengertian dan definisi Artificial Intelligence (AI) secara komprehensif?")
    add_para(doc, "2. Bagaimana sejarah dan perkembangan AI dari masa ke masa?")
    add_para(doc, "3. Apa saja jenis-jenis AI berdasarkan berbagai klasifikasi?")
    add_para(doc, "4. Bagaimana cara kerja dan teknologi yang mendasari AI?")
    add_para(doc, "5. Apa saja implementasi AI dalam berbagai bidang kehidupan?")
    add_para(doc, "6. Apa manfaat dan dampak positif AI bagi kehidupan manusia?")
    add_para(doc, "7. Apa saja dampak negatif dan tantangan dari perkembangan AI?")
    add_para(doc, "8. Bagaimana prospek dan masa depan AI ke depan?")
    add_para(doc, "9. Apa saja isu etika yang berkaitan dengan pengembangan AI?")
    add_para(doc, "10. Bagaimana regulasi dan kebijakan yang mengatur penggunaan AI?")
    
    add_bold(doc, "1.3 Tujuan Penulisan")
    add_para(doc, "Berdasarkan rumusan masalah yang telah ditetapkan, maka tujuan dari penulisan laporan ini adalah:")
    add_para(doc, "1. Menjelaskan pengertian dan definisi Artificial Intelligence secara komprehensif berdasarkan berbagai perspektif para ahli.")
    add_para(doc, "2. Menguraikan sejarah dan perkembangan AI dari awal muncul hingga kondisi saat ini, termasuk milestone penting yang menandai kemajuan AI.")
    add_para(doc, "3. Mengidentifikasi dan mengklasifikasikan jenis-jenis AI berdasarkan kapabilitas, fungsi, dan teknologi yang digunakan.")
    add_para(doc, "4. Memahami cara kerja AI, termasuk konsep machine learning, deep learning, neural networks, dan teknologi terkait lainnya.")
    add_para(doc, "5. Menganalisis implementasi AI dalam berbagai sektor kehidupan, termasuk kesehatan, pendidikan, ekonomi, transportasi, hiburan, dan pemerintahan.")
    add_para(doc, "6. Mengevaluasi manfaat dan dampak positif AI dalam meningkatkan efisiensi, produktivitas, dan kualitas hidup manusia.")
    add_para(doc, "7. Mengidentifikasi dampak negatif AI seperti pengangguran teknologis, bias algoritma, ancaman privasi, dan risiko keamanan.")
    add_para(doc, "8. Meramalkan prospek dan tren perkembangan AI di masa depan, termasuk teknologi yang diharapkan появится.")
    add_para(doc, "9. Membahas isu-isu etika yang muncul dari pengembangan dan penggunaan AI dalam berbagai konteks.")
    add_para(doc, "10. Mengkaji regulasi dan kebijakan yang diperlukan untuk mengatur pengembangan dan penggunaan AI secara bertanggung jawab.")
    
    add_bold(doc, "1.4 Manfaat Penulisan")
    add_para(doc, "Diharapkan laporan ini dapat memberikan manfaat sebagai berikut:")
    add_para(doc, "a. Manfaat Teoritis:")
    add_para(doc, "   - Menambah khazanah pengetahuan mengenai Artificial Intelligence")
    add_para(doc, "   - Menjadi referensi bagi pembaca yang ingin mendalami bidang AI")
    add_para(doc, "   - Memberikan gambaran komprehensif tentang perkembangan AI terkini")
    add_para(doc, "b. Manfaat Praktis:")
    add_para(doc, "   - Membantu pembaca memahami aplikasi AI dalam kehidupan sehari-hari")
    add_para(doc, "   - Memberikan insight tentang peluang dan tantangan AI di berbagai bidang")
    add_para(doc, "   - Menjadi bahan pertimbangan dalam pengambilan keputusan terkait adopt teknologi AI")
    
    add_bold(doc, "1.5 Ruang Lingkup dan Batasan")
    add_para(doc, "Untukmemfokuskan pembahasan, laporan ini dibatasi pada:")
    add_para(doc, "1. Fokus pada AI dalam konteks komputasi dan teknologi informasi")
    add_para(doc, "2. Pembahasan mencakup aspek teknis, aplikasi, dampak, dan implikasi sosial AI")
    add_para(doc, "3. Data dan informasi yang digunakan berasal dari sumber-sumber terpercaya hingga tahun 2026")
    add_para(doc, "4. Pembahasan tidak mencakup secara detail aspek pemrograman atau implementasi teknis AI")
    
    add_bold(doc, "1.6 Sistematika Penulisan")
    add_para(doc, "Laporan ini disusun dengan sistematika sebagai berikut:")
    add_para(doc, "BAB I   : PENDAHULUAN")
    add_para(doc, "         Berisi latar belakang, rumusan masalah, tujuan, manfaat, ruang lingkup, dan sistematika penulisan.")
    add_para(doc, "BAB II  : LANDASAN TEORI")
    add_para(doc, "         Memuat teori-teori tentang AI, termasuk definisi, jenis, teknologi, dan konsep dasar lainnya.")
    add_para(doc, "BAB III : METODE PENULISAN")
    add_para(doc, "         Menjelaskan metode yang digunakan dalam penyusunan laporan.")
    add_para(doc, "BAB IV  : PEMBAHASAN")
    add_para(doc, "         Bagian inti laporan yang membahas berbagai aspek AI secara mendalam dan komprehensif.")
    add_para(doc, "BAB V   : KESIMPULAN DAN SARAN")
    add_para(doc, "         Berisi kesimpulan dari seluruh pembahasan serta saran untuk pembaca dan pihak terkait.")
    
    doc.add_page_break()

    # BAB II - LANDASAN TEORI
    add_heading(doc, "BAB II. LANDASAN TEORI")
    
    add_bold(doc, "2.1 Pengertian Artificial Intelligence")
    add_para(doc, "Artificial Intelligence (AI) atau Kecerdasan Buatan adalah cabang dari ilmu komputer yang berfokus pada pembuatan sistem dan mesin yang mampu melakukan tugas-tugas yang umumnya memerlukan kecerdasan manusia. Tugas-tugas tersebut meliputi pembelajaran, penalaran, pemecahan masalah, pemahaman bahasa, pengenalan pola, dan pengambilan keputusan.")
    add_para(doc, "Menurut definição yang dikemukakan oleh Stuart Russell dan Peter Norvig dalam bukunya \"Artificial Intelligence: A Modern Approach\", AI memiliki empat definisi berbeda berdasarkan cara berpikir dan perilakunya:")
    add_para(doc, "1. Thinking Humanly - Cognitive Modeling: AI sebagai sistem yang dapat berpikir seperti manusia")
    add_para(doc, "2. Thinking Rationally - Laws of Thought: AI sebagai sistem yang dapat berpikir secara rasional")
    add_para(doc, "3. Acting Humanly - Turing Test: AI sebagai sistem yang dapat bertindak seperti manusia")
    add_para(doc, "4. Acting Rationally - Rational Agent: AI sebagai sistem yang dapat bertindak secara rasional")
    add_para(doc, "John McCarthy, yang dikenal sebagai \"Father of AI\", mendefinisikan AI sebagai \"the science and engineering of making intelligent machines, especially intelligent computer programs\". Definisi ini menekankan bahwa AI berkaitan dengan penggunaan metode komputasional untuk membuat mesin dapat menampilkan perilaku yang dianggap sebagai kecerdasan.")
    add_para(doc, "Selain itu, berbagai definisi lain dari para ahli juga memberikan perspektif yang berbeda mengenai AI:")
    add_para(doc, "- Elaine Rich (1983): AI adalah studi tentang cara membuat komputer melakukan hal-hal yang pada saat ini dapat dilakukan lebih baik oleh manusia.")
    add_para(doc, "- Robert J. Schalkopf (1994): AI adalah automasi dari aktivitas yang kita kaitkan dengan pemikiran manusia, aktivitas seperti pengambilan keputusan, pemecahan masalah, dan pembelajaran.")
    add_para(doc, "- David L. Poole dan Alan K. Mackworth (2010): AI adalah studi tentang reaktif, proaktif, dan interaksi cerdas yang berevolusi.")
    add_para(doc, "Secara sederhana, AI dapat dipahami sebagai kemampuan sistem komputer untuk meniru fungsi kognitif manusia seperti belajar, memecahkan masalah, dan membuat keputusan.")
    
    add_bold(doc, "2.2 Sejarah dan Perkembangan AI")
    add_para(doc, "Sejarah Artificial Intelligence bermula pada pertengahan abad ke-20 dan dapat dibagi menjadi beberapa era penting:")
    
    add_bold(doc, "2.2.1 Era Perintis (1943-1956)")
    add_para(doc, "Pada tahun 1943, Warren McCulloch dan Walter Pitts menciptakan model neuron buatan yang menjadi dasar pengembangan neural networks. Mereka menunjukkan bahwa fungsi-fungsi sederhana dapat dihitung oleh jaringan neuron buatan.")
    add_para(doc, "Pada tahun 1950, Alan Turing mengembangkan \"Turing Test\" sebagai ukuran kecerdasan mesin. Dalam tes ini, seorang interogator manusia akan berkomunikasi dengan mesin dan manusia lain melalui terminal teks. Jika interogator tidak dapat membedakan mana mesin dan manusia, maka mesin tersebut dianggap memiliki kecerdasan.")
    add_para(doc, "Pada tahun 1956, terjadi peristiwa bersejarah yang menandai kelahiran AI sebagai bidang ilmu. Di Dartmouth College, Hanover, New Hampshire, John McCarthy, Marvin Minsky, Claude Shannon, dan Nathaniel Rochester organise Dartmouth Conference. Dalam konferensi inilah istilah \"Artificial Intelligence\" pertama kali digunakan secara resmi. Acara ini sering disebut sebagai \"Dartmouth Summer Research Project on Artificial Intelligence\" dan menjadi awal dari era penelitian AI modern.")
    
    add_bold(doc, "2.2.2 Era Golden Age (1956-1974)")
    add_para(doc, "Setelah Dartmouth Conference, penelitian AI berkembang pesat. Berbagai program AI berhasil dibuat, termasuk Logic Theorist (1956) yang merupakan program AI pertama yang dirancang untuk membuktikan teorema matematika. Shakey the Robot (1966) juga появился sebagai robot pertama yang dapat menganalisis perintah dan menavigasi ruangan secara mandiri.")
    add_para(doc, "Durante periode ini, optimisme tinggi menyelimuti komunitas AI. Banyak peneliti memprediksi bahwa mesin yang setara dengan inteligensi manusia akan segera menjadi kenyataan. Pada tahun 1965, Herbert Simon memprediksi bahwa dalam 10 tahun, mesin akan menjadi juara dunia catur. Prediksi ini, meskipun tidak tepat waktu, pada akhirnya menjadi kenyataan ketika Deep Blue mengalahkan Garry Kasparov pada tahun 1997.")
    add_para(doc, "Namun, keterbatasan mulai terasa. Komputer pada masa itu tidak memiliki kecepatan dan kapasitas memori yang cukup untuk memproses informasi yang kompleks. Selain itu, banyak masalah AI yang terbukti lebih sulit dari yang diperkirakan. Pendanaan untuk penelitian AI mulai berkurang drastis, menandai dimulainya periode yang dikenal sebagai \"AI Winter\".")
    
    add_bold(doc, "2.2.3 AI Winter (1974-1980)")
    add_para(doc, "AI Winter adalah periode penurunan minat dan pendanaan terhadap penelitian AI. Durante waktu ini, banyak program AI yang gagal memenuhi ekspektasi tinggi yang telah ditetapkan. Kritik dari dalam dan luar komunitas AI semakin keras. LAPTOP (Logic Programming) dan sistem berbasis pengetahuan menjadi fokus baru, tetapi kemajuan tetap lambat.")
    add_para(doc, "Masalah utama yang dihadapi AI saat itu adalah:")
    add_para(doc, "1. Keterbatasan komputasi - komputer terlalu lambat dan mahal")
    add_para(doc, "2. Keterbatasan memori - tidak cukup untuk menyimpan knowledge base yang besar")
    add_para(doc, "3. Masalah commonsense knowledge - mesin tidak memiliki pemahaman tentang dunia nyata")
    add_para(doc, "4. Keterbatasan dalam pemrosesan bahasa alami")
    
    add_bold(doc, "2.2.4 Kebangkitan Kembali (1980-1987)")
    add_para(doc, "Pada tahun 1980, AI mengalami kebangkitan dengan introduction of Expert Systems. Berbeda dengan program AI sebelumnya yang berbasis rules sederhana, expert systems menggunakan knowledge base yang besar dan rules inferensi yang kompleks untuk meniru keputusan manusia dalam domain spesifik.")
    add_para(doc, "XCON (eXpert CONfigurer), yang dikembangkan oleh Digital Equipment Corporation pada tahun 1980, menjadi salah satu expert system paling sukses. Sistem ini digunakan untuk mengkonfigurasi komputer VAX dan menghemat perusahaan diperkirakan $40 juta per tahun.")
    add_para(doc, "Pada periode ini, Japan menjadi pemimpin dalam penelitian AI dengan proyek \"Fifth Generation Computer System\" (FGCS). Proyek ini bertujuan untuk membuat komputer yang dapat berkomunikasi dalam bahasa alami dan memecahkan masalah kompleks. Response dari Amerika Serikat adalah pendirian Microelectronics and Computer Technology Corporation (MCC) untuk tetap kompetitif.")
    
    add_bold(doc, "2.2.5 AI Winter Kedua (1987-1993)")
    add_para(doc, "Meskipun expert systems menunjukkan promise di awal, banyak yang mulai menyadari keterbatasan mereka. Expert systems sulit untuk di-maintain, tidak dapat belajar sendiri, dan seringkali fail dalam situasi di luar knowledge base mereka.")
    add_para(doc, "Pada saat yang sama, workstation yang lebih murah dan powerful mulai bermunculan, mengurangi permintaan untuk expensive dedicated AI systems. Perusahaan-perusahaan AI mulai gulung tikar atau beralih ke area penelitian lain. Industri AI berkurang drastis dari $1 miliar menjadi $800 juta.")
    
    add_bold(doc, "2.2.6 Era Modern (1993-Sekarang)")
    add_para(doc, "Desde 1993, AI mengalami renaissance yang luar biasa. Faktor-faktor yang mendasari kebangkitan ini meliputi:")
    add_para(doc, "1. Peningkatan kekuatan komputasi - hukum Moore memungkinkan pemrosesan data yang lebih cepat dan efisien")
    add_para(doc, "2. Ketersediaan data besar (Big Data) - internet menghasilkan data dalam jumlah yang belum pernah terjadi sebelumnya")
    add_para(doc, "3. Perkembangan algoritma machine learning dan deep learning")
    add_para(doc, "4. Penurunan biaya komputasi dan penyimpanan data")
    add_para(doc, "Beberapa milestone penting di era modern meliputi:")
    add_para(doc, "- 1997: Deep Blue mengalahkan Grandmaster catur Garry Kasparov")
    add_para(doc, "- 2002: Roomba, robot vacuum cleaner pertama, mulai dijual secara komersial")
    add_para(doc, "- 2011: Watson IBM menang di Jeopardy melawan champions")
    add_para(doc, "- 2011: Siri diperkenalkan oleh Apple")
    add_para(doc, "- 2012: AlexNet赢得 ImageNet Large Scale Visual Recognition Challenge dengan margin yang signifikan, mempopulerkan deep learning")
    add_para(doc, "- 2014: Google memperkenalkan TensorFlow")
    add_para(doc, "- 2016: AlphaGo mengalahkan Champion Go Lee Sedol")
    add_para(doc, "- 2018: GPT-1 (Generative Pre-trained Transformer) dikembangkan oleh OpenAI")
    add_para(doc, "- 2020: GPT-3 dirilis dengan 175 miliar parameter")
    add_para(doc, "- 2022: ChatGPT launched dan mendapatkan 100 juta pengguna dalam waktu singkat")
    add_para(doc, "- 2023: GPT-4 dirilis dengan kemampuan multimodal")
    add_para(doc, "- 2024: various AI models dengan kapabilitas advanced muncul")
    add_para(doc, "- 2025-2026: AI terintegrasi secara luas dalam berbagai produk dan layanan consumer")
    
    add_bold(doc, "2.3 Jenis-Jenis Artificial Intelligence")
    
    add_bold(doc, "2.3.1 Klasifikasi Berdasarkan Kapabilitas")
    add_para(doc, "Berdasarkan kapabilitas atau kemampuan yang dimilikinya, AI dapat diklasifikasikan menjadi tiga kategori:")
    add_para(doc, "a) Narrow AI (Weak AI)")
    add_para(doc, "   Narrow AI, juga dikenal sebagai Weak AI, adalah sistem AI yang dirancang dan dilatih untuk menyelesaikan tugas spesifik tertentu. Sistem ini beroperasi dalam batasan yang telah ditentukan dan tidak memiliki kesadaran atau pemahaman di luar domain tugasnya. Sebagian besar AI yang kita gunakan saat ini termasuk dalam kategori ini.")
    add_para(doc, "   Contoh Narrow AI:")
    add_para(doc, "   - Siri, Alexa, Google Assistant (asisten virtual)")
    add_para(doc, "   - Spam filters di email")
    add_para(doc, "   - Rekomendasi Netflix dan Spotify")
    add_para(doc, "   - Chatbots customer service")
    add_para(doc, "   - Face recognition di smartphone")
    add_para(doc, "   - Autonomous vehicles dalam kondisi tertentu")
    add_para(doc, "")
    add_para(doc, "b) General AI (Strong AI)")
    add_para(doc, "   General AI, juga dikenal sebagai Strong AI atau AGI (Artificial General Intelligence), adalah hipotesis AI yang memiliki kemampuan kognitif sama dengan manusia di berbagai bidang. Sistem ini akan dapat memahami, belajar, dan menerapkan pengetahuan untuk menyelesaikan berbagai masalah tanpa intervention manusia.")
    add_para(doc, "   Sampai saat ini, AGI masih menjadi konsep teoretis dan belum ada sistem yang benar-benar mencapai level ini. Banyak ahli percaya bahwa AGI baru akan tercapai dalam beberapa dekade mendatang, sementara yang lain berpendapat bahwa hal tersebut mungkin tidak akan pernah terjadi.")
    add_para(doc, "")
    add_para(doc, "c) Super AI")
    add_para(doc, "   Super AI, atau Artificial Superintelligence (ASI), adalah hipotesis AI yang melampaui kecerdasan manusia dalam semua aspek, termasuk kreativitas, kecerdasan umum, dan sosial. Konsep ini pertama kali dikemukakan oleh Nick Bostrom dalam bukunya \"Superintelligence: Paths, Dangers, Strategies\".")
    add_para(doc, "   Jika Super AI tercapai, banyak yang khawatir tentang implikasinya terhadap umat manusia. Skenario ini sering disebut sebagai \"The Singularity\" - titik di mana AI dapat berkembang dengan sendirinya di luar kendali manusia.")
    
    add_bold(doc, "2.3.2 Klasifikasi Berdasarkan Fungsionalitas")
    add_para(doc, "Berdasarkan fungsionalitasnya, AI dapat diklasifikasikan menjadi empat tipe:")
    add_para(doc, "a) Reactive Machines")
    add_para(doc, "   Reactive machines adalah tipe AI paling sederhana yang hanya dapat merespons situasi tertentu tanpa menggunakan memori atau pengalaman masa lalu. Sistem ini tidak memiliki kemampuan untuk belajar dari pengalaman sebelumnya.")
    add_para(doc, "   Contoh: IBM Deep Blue yang mengalahkan Grandmaster catur Garry Kasparov. Sistem ini menganalisis posisi bidak di papan catur dan memilih langkah terbaik berdasarkan calculation, tetapi tidak mengingat gerakan sebelumnya.")
    add_para(doc, "")
    add_para(doc, "b) Limited Memory")
    add_para(doc, "   Limited memory AI memiliki kemampuan untuk menggunakan pengalaman masa lalu dalam pengambilan keputusan saat ini. Meskipun tidak memiliki memori jangka panjang seperti manusia, sistem ini dapat menyimpan dan menggunakan data sementara untuk meningkatkan kinerjanya.")
    add_para(doc, "   Contoh: Self-driving cars yang menggunakan data dari sensor untuk membuat keputusan driving. Sistem ini memantau kecepatan dan arah mobil lain, menggunakan data ini untuk membuat keputusan seperti kapan harus berubah jalur atau mengerem.")
    add_para(doc, "")
    add_para(doc, "c) Theory of Mind")
    add_para(doc, "   Theory of mind AI adalah konsep AI yang dapat memahami emosi, niat, kepercayaan, dan pikiran manusia. Kemampuan ini penting untuk interaksi manusia-AI yang natural dan efektif.")
    add_para(doc, "   Jenis AI ini masih dalam tahap pengembangan dan belum sepenuhnya realise. Researchers sedang bekerja untuk menciptakan sistem yang dapat memahami dan merespons emosi manusia dengan tepat.")
    add_para(doc, "")
    add_para(doc, "d) Self-Aware AI")
    add_para(doc, "   Self-aware AI adalah tipe AI hipotetis yang memiliki kesadaran diri, mirip dengan kesadaran manusia. AI jenis ini akan dapat memahami kondisinya sendiri, memiliki keinginan dan kebutuhan sendiri, serta mampu merasakan emosi.")
    add_para(doc, "   Saat ini, self-aware AI masih sepenuhnya berada dalam ranah fiksi ilmiah dan tidak ada kemajuan signifikan dalam menciptakan AI dengan kesadaran diri.")
    
    add_bold(doc, "2.4 Teknologi Pendukung AI")
    
    add_bold(doc, "2.4.1 Machine Learning")
    add_para(doc, "Machine Learning (ML) adalah subset dari AI yang memungkinkan sistem untuk belajar dan meningkatkan dari pengalaman tanpa diprogram secara eksplisit. ML berfokus pada development dari computer programs yang dapat mengakses data dan用它 untuk belajar sendiri.")
    add_para(doc, "Jenis-jenis Machine Learning:")
    add_para(doc, "a) Supervised Learning: ML menggunakan data berlabel untuk melatih model. Contoh: email spam detection, image classification.")
    add_para(doc, "b) Unsupervised Learning: ML menemukan pola dalam data tanpa label. Contoh: customer segmentation, anomaly detection.")
    add_para(doc, "c) Reinforcement Learning: ML belajar melalui trial and error dengan reward dan punishment. Contoh: game AI, autonomous driving.")
    add_para(doc, "d) Deep Learning: Subset dari ML yang menggunakan neural networks dengan banyak layers. Contoh: speech recognition, NLP.")
    
    add_bold(doc, "2.4.2 Deep Learning")
    add_para(doc, "Deep Learning adalah subbidang dari machine learning yang menggunakan neural networks berlapis (deep neural networks) untuk memodelkan dan memecahkan masalah yang kompleks. Istilah \"deep\" merujuk pada jumlah lapisan (hidden layers) dalam neural network.")
    add_para(doc, "Arsitektur Deep Learning yang populer:")
    add_para(doc, "- Convolutional Neural Networks (CNN): Digunakan untuk image recognition dan computer vision")
    add_para(doc, "- Recurrent Neural Networks (RNN): Digunakan untuk sequential data seperti text dan time series")
    add_para(doc, "- Transformers: Digunakan untuk NLP dan menjadi dasar model seperti GPT dan BERT")
    add_para(doc, "- Generative Adversarial Networks (GAN): Digunakan untuk menghasilkan data sintetis")
    
    add_bold(doc, "2.4.3 Natural Language Processing (NLP)")
    add_para(doc, "NLP adalah cabang dari AI yang berfokus pada interaksi antara komputer dan manusia melalui bahasa alami. NLP memungkinkan komputer untuk memahami, menginterpretasi, dan menghasilkan bahasa manusia.")
    add_para(doc, "Aplikasi NLP meliputi:")
    add_para(doc, "- Machine translation (Google Translate)")
    add_para(doc, "- Sentiment analysis")
    add_para(doc, "- Chatbots dan virtual assistants")
    add_para(doc, "- Text summarization")
    add_para(doc, "- Speech recognition")
    
    add_bold(doc, "2.4.4 Computer Vision")
    add_para(doc, "Computer Vision adalah bidang AI yang memungkinkan komputer untuk \"melihat\" dan memahami informasi dari gambar dan video. Teknologi ini menggunakan convolutional neural networks untuk mengidentifikasi dan mengklasifikasi objek dalam gambar.")
    add_para(doc, "Aplikasi Computer Vision:")
    add_para(doc, "- Facial recognition")
    add_para(doc, "- Autonomous vehicles")
    add_para(doc, "- Medical imaging analysis")
    add_para(doc, "- Quality control in manufacturing")
    add_para(doc, "- Augmented reality")
    
    add_bold(doc, "2.4.5 Neural Networks")
    add_para(doc, "Neural Networks terinspirasi oleh cara kerja otak manusia. Jaringan ini terdiri dari node (neurons) yang saling terhubung dan dapat belajar dari data. Setiap koneksi memiliki bobot yang dapat disesuaikan selama proses pembelajaran.")
    add_para(doc, "Komponen utama neural network:")
    add_para(doc, "- Input Layer: Menerima data input")
    add_para(doc, "- Hidden Layers: Memproses data melalui transformation")
    add_para(doc, "- Output Layer: Menghasilkan hasil prediksi atau klasifikasi")
    add_para(doc, "- Activation Functions: Menentukan output dari setiap neuron")
    
    doc.add_page_break()

    # BAB III - METODE
    add_heading(doc, "BAB III. METODE PENULISAN")
    
    add_bold(doc, "3.1 Jenis Penelitian")
    add_para(doc, "Metode penelitian yang digunakan dalam penyusunan laporan ini adalah metode penelitian kualitatif dengan pendekatan studi literatur (library research). Metode ini dipilih karena sesuai dengan nature dari laporan yang bersifat deskriptif-analitis dan berfokus pada pengkajian teori-teori yang sudah established di bidang AI.")
    
    add_bold(doc, "3.2 Teknik Pengumpulan Data")
    add_para(doc, "Teknik pengumpulan data yang digunakan meliputi:")
    add_para(doc, "1. Studi Literatur")
    add_para(doc, "   Pengumpulan data dilakukan melalui pembacaan dan pengkajian berbagai sumber literatur yang relevan, termasuk:")
    add_para(doc, "   - Buku-buku teks tentang Artificial Intelligence, Machine Learning, dan Deep Learning")
    add_para(doc, "   - Jurnal ilmiah dan paper penelitian dari conference AI terkemuka (NeurIPS, ICML, AAAI, dll)")
    add_para(doc, "   - Artikel dari situs web terpercaya seperti IEEE Spectrum, MIT Technology Review, Ars Technica")
    add_para(doc, "   - Publication dari perusahaan teknologi besar seperti Google AI, OpenAI, Meta AI, Microsoft Research")
    add_para(doc, "   - Laporan dari organisasi internasional seperti UNESCO, World Economic Forum, OECD")
    add_para(doc, "")
    add_para(doc, "2. Observasi")
    add_para(doc, "   Pengamatan terhadap implementasi AI dalam kehidupan sehari-hari dan berbagai produk teknologi yang menggunakan AI. Observation ini membantu memahami bagaimana teori AI diaplikasikan dalam praktik.")
    add_para(doc, "")
    add_para(doc, "3. Wawancara Tidak Terstruktur")
    add_para(doc, "   Perolehan informasi dari berbagai diskusi di forum online, podcast, dan video conference tentang perkembangan AI terkini.")
    
    add_bold(doc, "3.3 Teknik Analisis Data")
    add_para(doc, "Data yang telah dikumpulkan kemudian dianalisis menggunakan teknik sebagai berikut:")
    add_para(doc, "1. Reduksi Data: Memilih dan memfokuskan data yang paling relevan dengan topik laporan")
    add_para(doc, "2. Kategorisasi: Mengelompokkan data berdasarkan tema dan topik pembahasan")
    add_para(doc, "3. Sintesis: Menggabungkan berbagai sumber untuk membentuk gambaran utuh tentang AI")
    add_para(doc, "4. Interpretasi: Memberikan makna dan penjelasan terhadap data yang telah dianalisis")
    add_para(doc, "5. Komparasi: Membandingkan perspektif dan temuan dari berbagai sumber")
    
    add_bold(doc, "3.4 Alur Penyusunan")
    add_para(doc, "Proses penyusunan laporan mengikuti alur sebagai berikut:")
    add_para(doc, "1. Penentuan topik dan fokus pembahasan")
    add_para(doc, "2. Pengumpulan referensi dan sumber informasi")
    add_para(doc, "3. Pengkajian dan analisis literatur")
    add_para(doc, "4. Penyusunan kerangka laporan (outline)")
    add_para(doc, "5. Penulisan draft laporan")
    add_para(doc, "6. Review dan revisi konten")
    add_para(doc, "7. Finalisasi dan penyuntingan")
    
    doc.add_page_break()

    # BAB IV - PEMBAHASAN
    add_heading(doc, "BAB IV. PEMBAHASAN")
    
    add_bold(doc, "4.1 Implementasi AI dalam Berbagai Bidang")
    
    add_bold(doc, "4.1.1 Bidang Kesehatan")
    add_para(doc, "Implementasi AI dalam bidang kesehatan telah membawa revolusi dalam cara pasien didiagnosis dan diobati. Beberapa contoh konkret meliputi:")
    add_para(doc, "a) Diagnosis Medis")
    add_para(doc, "   AI telah berhasil digunakan untuk mendeteksi berbagai penyakit dengan akurasi yang sebanding atau bahkan melampaui dokter manusia. Contohnya:")
    add_para(doc, "   - Google DeepMind's AI dapat mendeteksi eye diseases dengan akurasi 94,5%")
    add_para(doc, "   - AI untuk deteksi cancer kulit dapat mengidentifikasi melanoma dengan akurasi 95%")
    add_para(doc, "   - IBM Watson for Oncology membantu oncologists dalam merencanakan treatment untuk cancer")
    add_para(doc, "")
    add_para(doc, "b) Drug Discovery")
    add_para(doc, "   AI mempercepat proses pengembangan obat baru yang biasanya memakan waktu 10-15 tahun menjadi hanya beberapa tahun. AlphaFold dari DeepMind dapat memprediksi struktur protein dengan akurasi tinggi, revolutionize struktur protein determination.")
    add_para(doc, "")
    add_para(doc, "c) Robot Bedah")
    add_para(doc, "   Sistem robot bedah seperti Da Vinci Surgical System memungkinkan operasi dengan presisi tinggi, minimally invasive, dan waktu pemulihan pasien yang lebih cepat.")
    add_para(doc, "")
    add_para(doc, "d) Personalized Medicine")
    add_para(doc, "   AI menganalisis genetic, medical history, dan lifestyle pasien untuk memberikan treatment yang dipersonalisasi untuk setiap individu.")
    
    add_bold(doc, "4.1.2 Bidang Pendidikan")
    add_para(doc, "Transformasi digital di sektor pendidikan telah dipercepat oleh AI. Berbagai aplikasi AI dalam pendidikan meliputi:")
    add_para(doc, "a) Adaptive Learning")
    add_para(doc, "   Platform seperti Khan Academy dan Coursera menggunakan AI untuk mempersonalisasi pengalaman belajar. AI menganalisis cara belajar dan performa siswa untuk memberikan materi yang sesuai dengan level dan kebutuhan masing-masing.")
    add_para(doc, "")
    add_para(doc, "b) Intelligent Tutoring Systems")
    add_para(doc, "   AI tutors seperti Carnegie Learning menyediakan bimbingan personal yang dapat available 24/7. Sistem ini dapat menjelaskan konsep, menjawab pertanyaan, dan memberikan umpan balik seperti tutor manusia.")
    add_para(doc, "")
    add_para(doc, "c) Automated Grading")
    add_para(doc, "   AI dapat menilai esai dan jawaban terbuka dengan akurasi yang sebanding dengan human graders. Beberapa universities telah menggunakan sistem ini untuk menghemat waktu dan resources.")
    add_para(doc, "")
    add_para(doc, "d) Language Learning")
    add_para(doc, "   Aplikasi seperti Duolingo menggunakan AI untuk mempersonalisasi lesson plans dan mengidentifikasi area di mana siswa memerlukan practice lebih.")
    
    add_bold(doc, "4.1.3 Bidang Ekonomi dan Keuangan")
    add_para(doc, "Sektor keuangan telah menjadi early adopter AI. Implementasinya meliputi:")
    add_para(doc, "a) Algorithmic Trading")
    add_para(doc, "   Lebih dari 60% trades di pasar saham AS dilakukan oleh algoritma AI. High-frequency trading algorithms dapat menganalisis market data dan execute trades dalam milidetik.")
    add_para(doc, "")
    add_para(doc, "b) Fraud Detection")
    add_para(doc, "   Banks menggunakan AI untuk mendeteksi transaksi mencurigakan secara real-time. Machine learning models dapat mengidentifikasi pola fraud yang tidak dapat dideteksi oleh humans.")
    add_para(doc, "")
    add_para(doc, "c) Credit Scoring")
    add_para(doc, "   AI menganalisis berbagai data points untuk menentukan creditworthiness seseorang. Hal ini memungkinkan lebih banyak orang untuk acceder a crédito, termasuk mereka yang tidak memiliki traditional credit history.")
    add_para(doc, "")
    add_para(doc, "d) Customer Service")
    add_para(doc, "   Chatbots dan virtual assistants di banks dapat menangani pertanyaan customer service 24/7, mengurangi wait times dan meningkatkan customer satisfaction.")
    
    add_bold(doc, "4.1.4 Bidang Transportasi")
    add_para(doc, "AI merevolutionize industri transportasi:")
    add_para(doc, "a) Autonomous Vehicles")
    add_para(doc, "   Mobil self-driving dari Tesla, Waymo, dan Cruise menggunakan kombinasi computer vision, sensor fusion, dan deep learning untuk navigate tanpa human driver. Level 4 dan 5 autonomy sedang dalam pengembangan.")
    add_para(doc, "")
    add_para(doc, "b) Traffic Management")
    add_para(doc, "   AI mengoptimalkan lalu lintas dengan menganalisis data dari sensors dan cameras. Kota-kota seperti Singapore dan Los Angeles menggunakan AI untuk mengurangi congestion dan emissions.")
    add_para(doc, "")
    add_para(doc, "c) Public Transportation")
    add_para(doc, "   AI digunakan untuk route optimization, predictive maintenance, dan scheduling pada sistem transportasi publik di seluruh dunia.")
    add_para(doc, "")
    add_para(doc, "d) Delivery Drones dan Robots")
    add_para(doc, "   Companies seperti Amazon dan Domino's Pizza mengembangkan drone delivery dan robots untuk last-mile delivery.")
    
    add_bold(doc, "4.1.5 Bidang Hiburan dan Media")
    add_para(doc, "Industri hiburan telah transformed oleh AI:")
    add_para(doc, "a) Content Recommendation")
    add_para(doc, "   Netflix, Spotify, dan YouTube menggunakan AI untuk menganalisis preferensi pengguna dan memberikan rekomendasi yang personalized. 80% dari konten yang ditonton di Netflix berasal dari recommendations.")
    add_para(doc, "")
    add_para(doc, "b) Game AI")
    add_para(doc, "   NPC (Non-Player Characters) dalam video games menjadi lebih intelligent dan dapat merespons tindakan player dengan cara yang lebih natural.")
    add_para(doc, "")
    add_para(doc, "c) Music dan Art Generation")
    add_para(doc, "   AI seperti Amper Music dan DALL-E dapat menghasilkan musik dan gambar original. Meskipun masih kontroversial, teknologi ini membuka new possibilities untuk kreatif expression.")
    add_para(doc, "")
    add_para(doc, "d) Video Production")
    add_para(doc, "   AI digunakan untuk video editing, special effects, dan bahkan scriptwriting di industri film.")
    
    add_bold(doc, "4.1.6 Bidang Pemerintahan")
    add_para(doc, "Pemerintah di berbagai negara都开始采用 AI untuk meningkatkan layanan publik:")
    add_para(doc, "a) Smart Cities")
    add_para(doc, "   Kota pintar menggunakan AI untuk manajemen energi, waste management, pollution monitoring, dan public safety. Singapore, Barcelona, dan Songdo adalah contoh smart cities terkemuka.")
    add_para(doc, "")
    add_para(doc, "b) Public Services")
    add_para(doc, "   Chatbots pemerintah dapat menangani pertanyaan warga tentang layanan publik, mengurangi beban staff dan meningkatkan accessibility.")
    add_para(doc, "")
    add_para(doc, "c) Defense dan Security")
    add_para(doc, "   AI digunakan dalam cybersecurity, surveillance, dan bahkan dalam pengembangan autonomous weapons systems. Hal ini menimbulkan isu etis yang kompleks.")
    add_para(doc, "")
    add_para(doc, "d) Policy Making")
    add_para(doc, "   AI membantu pemerintah dalam analyzing data untuk kebijakan publik yang lebih informed.")
    
    add_bold(doc, "4.2 Manfaat Artificial Intelligence")
    
    add_bold(doc, "4.2.1 Peningkatan Efisiensi dan Produktivitas")
    add_para(doc, "AI dapat beroperasi 24/7 tanpa kelelahan, menghasilkan output yang konsisten dan mengurangi errors yang disebabkan oleh kelelahan manusia. Automasi tugas repetitif memungkinkan manusia untuk fokus pada tugas yang lebih kreatif dan bernilai tinggi.")
    add_para(doc, "McKinsey Global Institute reports bahwa AI dan automasi dapat meningkatkan global productivity growth sebesar 0.8-1.4% annually.")
    
    add_bold(doc, "4.2.2 Pengambilan Keputusan yang Lebih Baik")
    add_para(doc, "AI dapat menganalisis volume data yang jauh lebih besar daripada kemampuan manusia, menghasilkan insights yang dapat menginformasikan keputusan bisnis dan kebijakan publik. Data-driven decision making mengurangi bias dan meningkatkan akurasi prediksi.")
    
    add_bold(doc, "4.2.3 Inovasi dan Penciptaan Nilai Ekonomi Baru")
    add_para(doc, "AI membuka peluang untuk produk dan layanan baru yang sebelumnya tidak mungkin. Dari personalized medicine hingga autonomous vehicles, AI menciptakan industri baru dan mengubah yang existing.")
    add_para(doc, "PwC memprediksi bahwa AI akan menambah $15.7 trillion ke global economy pada 2030.")
    
    add_bold(doc, "4.2.4 Peningkatan Kualitas Hidup")
    add_para(doc, "Dari asisten virtual yang membantu daily tasks hingga AI dalam healthcare yang menyelamatkan nyawa, AI berkontribusi pada peningkatan quality of life secara keseluruhan.")
    
    add_bold(doc, "4.3 Dampak Negatif dan Tantangan AI")
    
    add_bold(doc, "4.3.1 Pengangguran Technological")
    add_para(doc, "World Economic Forum memprediksi bahwa AI akan menggantikan 85 juta jobs pada 2025 dan 375 million jobs pada 2030. Pekerjaan yang bersifat repetitif dan routin paling rentan terhadap automasi.")
    add_para(doc, "Namun, AI juga menciptakan new jobs - diperkirakan 97 million new jobs akan terbuat karena AI pada 2025. Tantangannya adalah memastikan workforce memiliki skills yang diperlukan untuk transisi ini.")
    
    add_bold(doc, "4.3.2 Bias dan Diskriminasi Algoritma")
    add_para(doc, "AI dapat mewarisi dan memperkuat bias dari data pelatihan. Contoh terkenal meliputi:")
    add_para(doc, "- Amazon's recruiting AI yang menunjukkan bias terhadap wanita")
    add_para(doc, "- COMPAS recidivism algorithm yang menunjukkan bias rasial")
    add_para(doc, "- Facial recognition systems dengan akurasi lebih rendah untuk people of color")
    add_para(doc, "Mengatasi bias dalam AI memerlukan diversifikasi data pelatihan, algorithmic fairness techniques, dan diverse teams dalam pengembangan AI.")
    
    add_bold(doc, "4.3.3 Ancaman Privasi")
    add_para(doc, "AI surveillance technologies menimbulkan kekhawatiran serius tentang privasi. Facial recognition, data collection, dan behavioral tracking dapat digunakan untuk pengawasan masif.")
    add_para(doc, "Beberapa negara telah implement peraturan ketat tentang penggunaan AI surveillance, sementara yang lain masih berjuang menemukan balance antara security dan privacy.")
    
    add_bold(doc, "4.3.4 Deepfakes dan Misinformasi")
    add_para(doc, "AI dapat membuat video, audio, dan gambar yang sangat meyakinkan tetapi sepenuhnya palsu. Deepfakes dapat digunakan untuk menyebarkan disinformasi, blackmail, dan fraud.")
    add_para(doc, "Deteksi deepfake menjadi semakin sulit seiring AI yang berkembang. Hal ini mengancam kepercayaan terhadap informasi dan media.")
    
    add_bold(doc, "4.3.5 Keamanan Siber")
    add_para(doc, "AI dapat digunakan untuk melancarkan cyber attacks yang lebih sophisticated. AI-powered attacks dapat bypass traditional security measures dan adapt terhadap defenses.")
    add_para(doc, "Di sisi lain, AI juga digunakan untuk memperkuat cybersecurity. Arms race antara AI-powered attacks dan defenses terus berlanjut.")
    
    add_bold(doc, "4.4 Isu Etika Artificial Intelligence")
    
    add_bold(doc, "4.4.1 Transparansi dan Explainability")
    add_para(doc, "Banyak AI systems, terutama deep learning models, beroperasi sebagai \"black boxes\" - input masuk dan output keluar, tetapi proses di antaranya sulit untuk dijelaskan. Hal ini menimbulkan проблема dalam aplikasi di mana penjelasan keputusan diperlukan, seperti dalam judicial system dan healthcare.")
    add_para(doc, "XAI (Explainable AI) adalah bidang penelitian yang berfokus pada pengembangan AI yang dapat dijelaskan dan dipahami oleh manusia.")
    
    add_bold(doc, "4.4.2 Akuntabilitas")
    add_para(doc, "Ketika AI membuat keputusan yang bermasalah, pertanyaan tentang siapa yang bertanggung jawab muncul. Apakah developer, perusahaan, atau user? Regulation yang jelas tentang akuntabilitas AI diperlukan.")
    
    add_bold(doc, "4.4.3 Hak Asasi Manusia")
    add_para(doc, "AI dapat digunakan untuk surveillance yang melanggar hak privasi, facial recognition yang diskriminatif, dan autonomous weapons yang dapat melukai civilians. Penggunaan AI harus menghormati hak asasi manusia sebagaimana dijamin oleh international law.")
    
    add_bold(doc, "4.4.4 Dampak Lingkungan")
    add_para(doc, "Training model AI besar membutuhkan energi yang sangat besar. Training GPT-3 diperkirakan menghasilkan carbon emissions setara dengan 500 ton CO2. Pertanyaan tentang sustainability AI yang responsible perlu addressed.")
    
    add_bold(doc, "4.5 Regulasi dan Kebijakan AI")
    
    add_bold(doc, "4.5.1 AI Act Uni Eropa")
    add_para(doc, "Uni Eropa telah mengadopsi AI Act, regulasi komprehensif pertama di dunia yang mengatur AI. AI Act mengklasifikasikan AI systems berdasarkan risk level:")
    add_para(doc, "- Unacceptable Risk: AI yang dilarang (social scoring, real-time biometric surveillance)")
    add_para(doc, "- High Risk: AI yang memerlukan strict oversight (medical devices, critical infrastructure)")
    add_para(doc, "- Limited Risk: AI dengan transparency requirements (chatbots)")
    add_para(doc, "- Minimal Risk: AI yang dapat digunakan tanpa restrictions")
    
    add_bold(doc, "4.5.2 Regulasi di Negara Lain")
    add_para(doc, "- Amerika Serikat: Pendekatan sektoral dengan executive orders dari Biden Administration pada 2023")
    add_para(doc, "- China: AI regulations focusing pada algorithmic recommendations dan generative AI")
    add_para(doc, "- Indonesia: Baru memulai discussions tentang AI governance dengan release dari blueprint AI nasional")
    
    add_bold(doc, "4.5.3 Prinsip Etika AI Global")
    add_para(doc, "UNESCO telah mengadopsi recommendation on AI ethics pada 2021, mencakup:")
    add_para(doc, "- Respect, protection and promotion of human rights and fundamental freedoms")
    add_para(doc, "- Democratic values and fairness")
    add_para(doc, "- Peaceful, just and interconnected societies")
    add_para(doc, "- Environmental and ecosystem flourishing")
    add_para(doc, "- Diversity and inclusiveness")
    
    add_bold(doc, "4.6 Prospek Masa Depan AI")
    
    add_bold(doc, "4.6.1 Tren yang Diprediksi")
    add_para(doc, "Beberapa tren AI yang diharapkan berkembang:")
    add_para(doc, "- Multimodal AI: AI yang dapat memproses teks, gambar, audio, dan video secara bersamaan")
    add_para(doc, "- AI Agents: Autonomous AI systems yang dapat melakukan tasks kompleks dengan minimal human intervention")
    add_para(doc, "- Edge AI: AI processing di device lokal daripada di cloud")
    add_para(doc, "- AI in Science: AI accelerating scientific discovery dalam fisika, chemistry, biology")
    add_para(doc, "- Quantum AI: Kombinasi quantum computing dengan AI untuk memecahkan problems yang currently unsolvable")
    
    add_bold(doc, "4.6.2 Artificial General Intelligence (AGI)")
    add_para(doc, "Apakah AGI akan tercapai? Opinions para ahli terbagi:")
    add_para(doc, "- Ray Kurzweil (Google): AGI pada 2029 dengan probability 50%")
    add_para(doc, "- Demis Hassabis (DeepMind): AGI dalam 10-20 tahun mungkin")
    add_para(doc, "- Yann LeCun (Meta): AGI membutuhkan breakthroughs baru, tidak dalam dekat future")
    add_para(doc, "- Stuart Russell: AGI memerlukan different approach, timeline uncertain")
    
    add_bold(doc, "4.6.3 Kolaborasi Manusia-AI")
    add_para(doc, "Masa depan yang lebih likely adalah symbiotic relationship antara manusia dan AI, bukan replacement. Human-AI collaboration dapat leverage strengths masing-masing:")
    add_para(doc, "- AI: Data processing, pattern recognition, tireless computation")
    add_para(doc, "- Human: Creativity, empathy, ethical judgment, common sense")
    
    doc.add_page_break()

    # BAB V - KESIMPULAN
    add_heading(doc, "BAB V. KESIMPULAN DAN SARAN")
    
    add_bold(doc, "5.1 Kesimpulan")
    add_para(doc, "Berdasarkan pembahasan yang telah diuraikan secara komprehensif dalam laporan ini, dapat ditarik beberapa kesimpulan sebagai berikut:")
    add_para(doc, "")
    add_para(doc, "1. Artificial Intelligence (AI) merupakan teknologi yang memungkinkan mesin untuk meniru kecerdasan manusia dalam menyelesaikan berbagai tugas. AI telah berkembang pesat sejak diperkenalkan pada tahun 1956 dan kini menjadi bagian integral dari kehidupan modern.")
    add_para(doc, "")
    add_para(doc, "2. AI memiliki berbagai jenis dengan kapabilitas yang berbeda-beda, dari Reactive Machines yang sederhana hingga konsep Super AI yang hipotetis. Sebagian besar AI saat ini termasuk dalam kategori Narrow AI yang hanya mampu menyelesaikan tugas spesifik tertentu.")
    add_para(doc, "")
    add_para(doc, "3. Teknologi pendukung AI seperti Machine Learning, Deep Learning, Natural Language Processing, dan Computer Vision telah berkembang dengan pesat, memungkinkan aplikasi AI yang semakin sophisticated dan powerful.")
    add_para(doc, "")
    add_para(doc, "4. Implementasi AI telah merambah ke berbagai bidang kehidupan dengan manfaat signifikan, termasuk kesehatan (diagnosis, drug discovery), pendidikan (adaptive learning), ekonomi (algorithmic trading), transportasi (autonomous vehicles), hiburan (content recommendation), dan pemerintahan (smart cities).")
    add_para(doc, "")
    add_para(doc, "5. Di samping manfaat, AI juga membawa dampak negatif seperti pengangguran akibat automasi (diprediksi 85 juta pekerjaan tergantikan pada 2025), bias algoritma, pelanggaran privasi, deepfakes, dan ancaman keamanan siber. Tantangan-tantangan ini memerlukan perhatian serius dari berbagai pemangku kepentingan.")
    add_para(doc, "")
    add_para(doc, "6. Isu etika AI menjadi semakin penting, termasuk transparansi algoritma, akuntabilitas keputusan AI, perlindungan hak asasi manusia, dan dampak lingkungan dari training model AI yang besar.")
    add_para(doc, "")
    add_para(doc, "7. Berbagai negara dan organisasi internasional都开始 mengembangkan regulasi untuk AI. EU AI Act merupakan langkah signifikan dalam menciptakan framework regulasi untuk AI yang responsible.")
    add_para(doc, "")
    add_para(doc, "8. Prospek masa depan AI sangat menjanjikan dengan tren seperti multimodal AI, AI agents, dan kemungkinan pencapaian AGI. Kolaborasi manusia-AI diprediksi akan menjadi model yang dominan, bukan replacement manusia oleh AI.")
    add_para(doc, "")
    add_para(doc, "9. Keberhasilan pengembangan AI di masa depan sangat bergantung pada kemampuan kita untuk mengembangkan AI yang tidak hanya powerful, tetapi juga safe, fair, dan aligned dengan nilai-nilai manusia.")
    
    add_bold(doc, "5.2 Saran")
    add_para(doc, "Berdasarkan kesimpulan di atas, beberapa saran yang dapat disampaikan adalah:")
    add_para(doc, "")
    add_para(doc, "1. Bagi Pemerintah:")
    add_para(doc, "   - Mengembangkan regulasi dan kebijakan nasional tentang AI")
    add_para(doc, "   - Meningkatkan investasi dalam penelitian dan pengembangan AI")
    add_para(doc, "   - Mempersiapkan workforce untuk transisi ke economy yang berbasis AI")
    add_para(doc, "   - Memastikan perlindungan privasi dan hak warga negara dalam penggunaan AI")
    add_para(doc, "")
    add_para(doc, "2. Bagi Institusi Pendidikan:")
    add_para(doc, "   - Mengintegrasikan AI literacy dalam kurikulum")
    add_para(doc, "   - Mempersiapkan siswa dengan skills yang diperlukan di era AI")
    add_para(doc, "   - Menggunakan AI untuk meningkatkan kualitas pendidikan")
    add_para(doc, "")
    add_para(doc, "3. Bagi Masyarakat:")
    add_para(doc, "   - Meningkatkan pemahaman tentang AI dan cara kerjanya")
    add_para(doc, "   - Bersikap kritis terhadap informasi yang dihasilkan AI")
    add_para(doc, "   - Memanfaatkan AI secara bertanggung jawab")
    add_para(doc, "")
    add_para(doc, "4. Bagi Developer dan Perusahaan Teknologi:")
    add_para(doc, "   - Mengedepankan ethical AI development")
    add_para(doc, "   - Memastikan transparansi dan akuntabilitas produk AI")
    add_para(doc, "   - Berkolaborasi dengan regulator dan masyarakat dalam pengembangan AI")
    add_para(doc, "   - Memperhatikan dampak lingkungan dari pengembangan AI")
    add_para(doc, "")
    add_para(doc, "5. Bagi Peneliti:")
    add_para(doc, "   - Terus mengembangkan teknologi AI yang aman dan beneficial")
    add_para(doc, "   - Penelitian tentang AI safety dan alignment")
    add_para(doc, "   - Interdisciplinary collaboration antara technologists, ethicists, dan social scientists")
    
    doc.add_page_break()
    
    # DAFTAR PUSTAKA
    add_heading(doc, "DAFTAR PUSTAKA")
    add_para(doc, "1. Russell, S. & Norvig, P. (2021). Artificial Intelligence: A Modern Approach. Fourth Edition. Pearson Education.")
    add_para(doc, "")
    add_para(doc, "2. McCarthy, J. (2007). What is Artificial Intelligence?. Stanford University.")
    add_para(doc, "")
    add_para(doc, "3. World Economic Forum. (2023). The Future of Jobs Report 2023. Geneva: WEF.")
    add_para(doc, "")
    add_para(doc, "4. Kaplan, A. & Haenlein, M. (2019). Siri, Siri, in my hand: Who's the fairest in the land? On the interpretations, illustrations, and implications of Artificial Intelligence. Business Horizons, 62(1), 15-25.")
    add_para(doc, "")
    add_para(doc, "5. Brynjolfsson, E. & McAfee, A. (2017). Machine, Platform, Crowd: Harnessing Our Digital Future. W.W. Norton & Company.")
    add_para(doc, "")
    add_para(doc, "6. UNESCO. (2021). Recommendation on the Ethics of Artificial Intelligence. Paris: UNESCO.")
    add_para(doc, "")
    add_para(doc, "7. European Commission. (2024). AI Act - Regulation on Artificial Intelligence. Brussels: EU.")
    add_para(doc, "")
    add_para(doc, "8. Bostrom, N. (2014). Superintelligence: Paths, Dangers, Strategies. Oxford University Press.")
    add_para(doc, "")
    add_para(doc, "9. Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.")
    add_para(doc, "")
    add_para(doc, "10.PwC. (2023). Global AI Study: Exploiting the AI Revolution. PricewaterhouseCoopers.")
    add_para(doc, "")
    add_para(doc, "11.McKinsey Global Institute. (2023). The State of AI in 2023: Generative AI's Breakout Year. McKinsey & Company.")
    add_para(doc, "")
    add_para(doc, "12.Stanford University. (2024). AI Index Report 2024. Stanford HAI.")
    add_para(doc, "")
    add_para(doc, "13.OpenAI. (2023). GPT-4 Technical Report. OpenAI.")
    add_para(doc, "")
    add_para(doc, "14.DeepMind. (2022). AlphaFold: A Solution to a 50-Year-Old Grand Challenge in Biology. DeepMind Technologies.")
    add_para(doc, "")
    add_para(doc, "15.Kurzweil, R. (2005). The Singularity Is Near: When Humans Transcend Biology. Viking Books.")
    
    doc.add_page_break()
    
    # LAMPIRAN
    add_heading(doc, "LAMPIRAN")
    
    add_bold(doc, "Lampiran A: Timeline Lengkap Perkembangan AI")
    add_para(doc, "1943 - Warren McCulloch dan Walter Pitts menciptakan model neuron buatan")
    add_para(doc, "1950 - Alan Turing mengembangkan Turing Test")
    add_para(doc, "1956 - Dartmouth Conference, istilah AI pertama kali digunakan")
    add_para(doc, "1958 - Frank Rosenblatt menciptakan Perceptron")
    add_para(doc, "1964 - ELIZA, chatbot pertama dikembangkan oleh Joseph Weizenbaum")
    add_para(doc, "1966 - Shakey the Robot, robot pertama dengan kemampuan reasoning")
    add_para(doc, "1969 - Marvin Minsky publish \"Perceptrons\" yang menunjukkan limitations")
    add_para(doc, "1974-1980 - AI Winter pertama")
    add_para(doc, "1980 - Expert Systems menjadi populer")
    add_para(doc, "1987-1993 - AI Winter kedua")
    add_para(doc, "1997 - Deep Blue defeating Garry Kasparov")
    add_para(doc, "1998 - Yann LeCun mengembangkan Convolutional Neural Networks untuk OCR")
    add_para(doc, "2002 - Roomba, robot consumer pertama")
    add_para(doc, "2006 - Geoffrey Hinton memperkenalkan Deep Belief Networks, rebranding deep learning")
    add_para(doc, "2011 - IBM Watson menang di Jeopardy")
    add_para(doc, "2011 - Siri diperkenalkan Apple")
    add_para(doc, "2012 - AlexNet menang ImageNet competition, mempopulerkan deep learning")
    add_para(doc, "2014 - Ian Goodfellow memperkenalkan GANs")
    add_para(doc, "2014 - Google memperkenalkan TensorFlow")
    add_para(doc, "2015 - TensorFlow menjadi open source")
    add_para(doc, "2016 - AlphaGo defeating Lee Sedol")
    add_para(doc, "2017 - Transformer architecture diperkenalkan dalam paper \"Attention Is All You Need\"")
    add_para(doc, "2018 - GPT-1 dan BERT diperkenalkan")
    add_para(doc, "2019 - GPT-2 dengan 1.5B parameters")
    add_para(doc, "2020 - GPT-3 dengan 175B parameters")
    add_para(doc, "2021 - AlphaFold2 memprediksi struktur protein")
    add_para(doc, "2022 - DALL-E 2 dan Stable Diffusion untuk image generation")
    add_para(doc, "2022 - ChatGPT launched")
    add_para(doc, "2023 - GPT-4 dengan multimodal capabilities")
    add_para(doc, "2023 - Claude, Gemini, dan berbagai LLM baru")
    add_para(doc, "2024 - AI video generation (Sora, Runway Gen-3)")
    add_para(doc, "2025 - AI agents mulai widespread")
    add_para(doc, "2026 - AI integrated dalam berbagai consumer products")
    
    doc.add_paragraph()
    add_bold(doc, "Lampiran B: Glossarium Istilah AI")
    add_para(doc, "AGI - Artificial General Intelligence: AI dengan kapabilitas kognitif umum seperti manusia")
    add_para(doc, "AI - Artificial Intelligence: Kecerdasan Buatan")
    add_para(doc, "ANN - Artificial Neural Network: Jaringan syaraf tiruan")
    add_para(doc, "API - Application Programming Interface")
    add_para(doc, "CNN - Convolutional Neural Network: Jenis deep neural network untuk gambar")
    add_para(doc, "DL - Deep Learning: Subbidang ML dengan neural networks berlapis")
    add_para(doc, "GAN - Generative Adversarial Network: Arsitektur untuk generate data sintetis")
    add_para(doc, "GPU - Graphics Processing Unit: Hardware untuk komputasi paralel")
    add_para(doc, "ML - Machine Learning: Subbidang AI untuk belajar dari data")
    add_para(doc, "NLP - Natural Language Processing: Kemampuan AI memahami bahasa")
    add_para(doc, "NN - Neural Network: Model komputasi terinspirasi otak")
    add_para(doc, "RNN - Recurrent Neural Network: NN untuk data sekuensial")
    add_para(doc, "RL - Reinforcement Learning: ML melalui trial and error")
    add_para(doc, "TF - Transfer Learning: Menggunakan knowledge dari satu task ke task lain")
    add_para(doc, "XAI - Explainable AI: AI yang dapat dijelaskan")
    
    doc.add_paragraph()
    add_bold(doc, "Lampiran C: Statistik AI 2026")
    add_para(doc, "Total market AI global: $500+ miliar")
    add_para(doc, "Jumlah pengguna AI: 4+ miliar orang")
    add_para(doc, "Investasi VC ke AI startup: $100+ miliar (2023-2025)")
    add_para(doc, "Pekerjaan yang terdampak AI: 375 juta global")
    add_para(doc, "Akurasi facial recognition AI terbaik: 99.97%")
    add_para(doc, "Model AI terbesar (GPT-4): ~1.8 triliun parameters")
    add_para(doc, "Energy untuk training GPT-3: ~3GWh")
    add_para(doc, "Waktu untuk training model besar: weeks to months")
    
    doc.add_paragraph()
    add_bold(doc, "Lampiran D: Tokoh-Tokoh Penting AI")
    add_para(doc, "John McCarthy - Father of AI, menciptakan istilah Artificial Intelligence")
    add_para(doc, "Marvin Minsky - Pionir AI, co-founder MIT AI Lab")
    add_para(doc, "Alan Turing - Bapak computer science, Turing Test")
    add_para(doc, "Geoffrey Hinton - Godfather of Deep Learning")
    add_para(doc, "Yann LeCun - Pionir CNN dan deep learning")
    add_para(doc, "Yoshua Bengio - Pionir deep learning, Turing Award winner")
    add_para(doc, "Demis Hassabis - CEO DeepMind, AlphaGo creator")
    add_para(doc, "Sam Altman - CEO OpenAI, ChatGPT creator")
    add_para(doc, "Fei-Fei Li - Pionir computer vision, ImageNet creator")
    add_para(doc, "Ray Kurzweil - Futurist, prediksi Singularity")
    add_para(doc, "Nick Bostrom - Filosof AI, Superintelligence author")
    add_para(doc, "Stuart Russell - AI researcher, Human Compatible author")
    add_para(doc, "Elon Musk - Co-founder OpenAI")
    add_para(doc, "Andrew Ng - AI educator dan researcher")
    
    output = "/root/.nullclaw/workspace/tasks/Laporan_Strategis_AI.docx"
    doc.save(output)
    return output

if __name__ == "__main__":
    out = buat_laporan()
    print(f"Generated: {out}")
    send_file(out)
    print("Dikirim ke Telegram")
